### ISSUE TITLE
:mega: Call for testers

### ISSUE THREAD

**Issue by PrinsFrank** [PrinsFrank/pdfparser#2]
Hi everyone!

Because of the immense complexity of PDF files there are a lot of different PDF formats and combinations of features that can be present in a single PDF file. 

It would really help if you could provide some feedback and test your PDF files. If you are the owner, generator of a PDF file or if you have permission to do so, it would also be really helpful if you could add it to the [sample-file repository ](https://github.com/PrinsFrank/pdf-samples) to include it in the tests!

**Comment by GreyWyvern** [comment]
What's the simplest way to use this? Just to load a PDF and extract all text. The documentation is pretty thin.

I used this:

```php
$test = new PrinsFrank\PdfParser\PdfParser();

$document = $test->parseFile([path to my PDF]);

$page = $document->getPage(1);

var_dump($page->getText($document));
```

... and got error: 

```
Fatal error:  Uncaught PrinsFrank\PdfParser\Exception\InvalidArgumentException: Expected value with value Contents to be of type PrinsFrank\PdfParser\Document\Dictionary\DictionaryValue\Reference\ReferenceValue, got PrinsFrank\PdfParser\Document\Dictionary\DictionaryValue\Reference\ReferenceValueArray in /path/to/pdfparser/Document/Dictionary/Dictionary.php:40
Stack trace:
#0 /path/to/pdfparser/Document/Object/Decorator/Page.php(23): PrinsFrank\PdfParser\Document\Dictionary\Dictionary-&gt;getValueForKey()
#1 /path/to/pdfparser/Document/Object/Decorator/Page.php(18): PrinsFrank\PdfParser\Document\Object\Decorator\Page-&gt;getTextObjectCollection()
#2 /path/to/pdfparser/Autoloader.php(157): PrinsFrank\PdfParser\Document\Object\Decorator\Page-&gt;getText()
#3 {main}
  thrown in /path/to/pdfparser/Document/Dictionary/Dictionary.php on line 40
```

I'm not using Composer. I created an auto-loader.

**Comment by PrinsFrank** [comment]
Thanks for the valuable feedback! I've added some more content to the readme and will add a lot more over the next few days. 

The code you supplied is indeed the correct way to get text from a page. I'll add another method to retrieve all text for a document.

The error you're running into is because the "Contents" dictionary key is expected to be a single reference, not a bunch of references. I'll need to dive into supporting these kinds of documents, and will let you know when those are supported!

Thanks for checking out the repo and for the valuable feedback, and I'll keep you updated!

**Comment by k00ni** [comment]
In the README you wrote that I can install it via Composer, but there is no package available. I would like to avoid handling Git repositories manually.

**Comment by PrinsFrank** [comment]
@k00ni I've made a release available!

**Comment by k00ni** [comment]
Should we keep posting each error/problem we found here or better create separate issues and add a link back to this issue?

I ran into the same problem @GreyWyvern reported. My "test environment" is https://github.com/k00ni/verkuendung-niedersachsen-plaintext, a private project which currently runs fine with `spatie/pdf-to-text`. I would like to see if you Parser produces better results. If you want to use it for local tests, you have to run the script once to get all PDFs.

Also, its more an opinion, but why does `Page::getText` needs a reference to a `Document` instance? I've got it through the `Document` instance, so I would assume the `Page` instance already has the reference. The need to give this reference again might also lead to mistakes if one uses different `Document` instances at the same time.

A method for the lazy (like me :smile:) to get all the text of a document would be great too, but that's more of a "quality of life" feature. On the other hand, iterating through each page allows me to decide how to connect each page. One might want to use nothing, others like a newline between each page.

**Comment by GreyWyvern** [comment]
I think if you want to get a head start, start by checking all the test PDF's from the original PdfParser's test suite. I went through a dozen or so of them that I have in my own test area and unfortunately this library did not parse a single one of them without errors, where the original PdfParser handles them okay. :D For now my project will keep using the original library, but I do agree that the original code is getting pretty unwieldy.

**Comment by PrinsFrank** [comment]
Thanks for all the valuable feedback! I've just published a new release which removes the `$document` argument on all decorators, and added a `getText` method on the document class.

Over the next few weeks I'll be quite busy as I'm moving, but I'll take a look at the samples from the smalot package and get them all to work. I'll add a new comment here once I've made significant progress!

**Comment by PrinsFrank** [comment]
I have spent quite some time the last few weeks on fixing all bugs and improving text extraction. Even though it can still be optimized and there will for sure be a bunch of edge cases left, I've just released the first stable release. Please check it out! If you have any feedback let me know! Thanks again for all the valuable feedback so far!
